# Generated by Django 3.1.2 on 2020-10-09 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='movieData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieName', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=10)),
                ('directorName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.director')),
            ],
        ),
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketPrice', models.IntegerField(default=0)),
                ('totalTickets', models.IntegerField(default=0)),
                ('ticketsSold', models.IntegerField(default=0)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.moviedata')),
            ],
        ),
        migrations.CreateModel(
            name='timeSlots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nTickets', models.IntegerField(default=1)),
                ('movieShow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.shows')),
            ],
        ),
        migrations.AddField(
            model_name='shows',
            name='timeSlots',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.timeslots'),
        ),
    ]
